name: Reset QA Branch

on:
  push:
    branches:
      - main

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Reset qa branch
        run: |
          git checkout main
          git pull
          git checkout qa
          git pull
          git reset main --hard
          git push -f
